begin;
drop policy if exists "System can update post counters" on public.posts;
drop policy if exists "Auth users can update own posts" on public.posts;
drop policy if exists "Users can update own posts" on public.posts;
create policy "Owners can update their own posts" on public.posts for update to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);
drop policy if exists "System can update comment upvotes" on public.comments;
drop policy if exists "Auth users can update own comments" on public.comments;
drop policy if exists "Users can update own comments" on public.comments;
create policy "Owners can update their own comments" on public.comments for update to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);
drop policy if exists "System can insert notifications" on public.notifications;
drop policy if exists "System can insert notification rows" on public.notifications;
revoke insert on table public.notifications from public, anon, authenticated;
drop policy if exists "Users can view own notifications" on public.notifications;
create policy "Users can view own notifications" on public.notifications for select to authenticated using(auth.uid()=user_id);
drop policy if exists "Users can update own notifications" on public.notifications;
create policy "Users can update own notifications" on public.notifications for update to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);
drop policy if exists "Users can delete own notifications" on public.notifications;
create policy "Users can delete own notifications" on public.notifications for delete to authenticated using(auth.uid()=user_id);
commit;